DROP TABLE laureates IF EXISTS;
DROP TABLE countries IF EXISTS;

CREATE TABLE laureates (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY(START WITH 2000, INCREMENT BY 1) PRIMARY KEY,
  first_name VARCHAR(50),
  last_name  VARCHAR(50),
  born varchar(10) ,
  died varchar(10) ,
  born_country varchar(45) ,
  born_country_code varchar(2),
  born_city varchar(45) ,
  died_country varchar(45) ,
  died_country_code varchar(2) ,
  gender varchar(1),
  prize_year INTEGER,
  category varchar(45) ,
  motivation varchar(3000) 
);

CREATE TABLE countries (
  countries_id INTEGER,
  iso varchar(2) ,
  iso_numeric INTEGER,
  name varchar(45) ,
  capital varchar(45) ,
  area INTEGER,
  population INTEGER,
  continent varchar(3) ,
  tld varchar(5) ,
  currency_code varchar(4) ,
  currency_name varchar(45) ,
  phone INTEGER,
  languages varchar(45)
);